### PR TITLE
Mobile support

### PR DESCRIPTION
**Pull request by roded**
#19 continued.

I'm not convinced regarding the mobile detection either.
But short of including a device-detection library which will regexp the user-agent, it seems like checking orientation should work appropriately.
MDN suggest checking the `Navigator` object's `maxTouchPoints` property (https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent) but that seems lacking as touch screen laptops are common.

For your consideration.

### CODE REVIEW

**Comment by yuvadm** [comment]
Looks great, thanks!

**Comment by roded** [comment]
Great, sure thing.
When can a new build be expected?

**Comment by yuvadm** [comment]
I'll try to do a release this weekend

**Comment by roded** [comment]
Hi, any update on a new build?
Thanks!

**Comment by yuvadm** [comment]
@roded Sorry this fell between the cracks, expect a release over the next hour

**Comment by roded** [comment]
No worries & many thanks

**Comment by yuvadm** [comment]
@roded Done! `v0.9.7` released

**Comment by roded** [comment]
Great! Mobile works just fine according to my tests.

**Pull request merged**
